name: repository_wrapper_generator
description: Code generator for repository wrappers in pomodoro
version: 0.0.1
environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  analyzer: ^7.4.5
  source_gen: ^3.1.0
  build: ^3.0.0

dev_dependencies:
  build_runner: ^2.7.1
