# build.yaml
targets:
  $default:
    builders:
      repository_wrapper_generator:
        enabled: true

builders:
  repository_wrapper_generator:
    target: ":repository_wrapper_generator"
    import: "package:repository_wrapper_generator/repository_wrapper_generator.dart"
    builder_factories: ["generateRepositoryWrapper"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
